spring:
  datasource:
    url: jdbc:postgresql://${PAYMENT_DB_HOST:localhost}:${PAYMENT_DB_PORT:5437}/${PAYMENT_DB_NAME:ecommerce_payments}
    username: ${PAYMENT_DB_USERNAME:postgres}
    password: ${PAYMENT_DB_PASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: localhost:9092

stripe:
  api-key: ${STRIPE_API_KEY:sk_test_51T9obaRU9nynbdRwdINFUiulliNbXBa2dtSrxHsbJLiHoSXd93LlSnqljpMWiGR5UNAB5WKvhK4gxcx2AM1NLD2000ApmcxZhW}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_9ed8a45f47d4a4ea08bdf6fafa051f065126f5b028d701082fbd91a9fc776070}

paypal:
  client-id: CHANGE_ME_AVEC_VRAI_CLIENT_ID_SANDBOX
  client-secret: CHANGE_ME_AVEC_VRAI_CLIENT_SECRET_SANDBOX
  mode: sandbox

logging:
  level:
    com.ecommerce.payment: DEBUG
    org.springframework.security: DEBUG
    org.springframework.kafka: DEBUG

external:
  kafka:
    enabled: false   # ← passer à true pour activer l'envoi externe
    bootstrap-servers: 136.115.254.39:9092
    topic: ecommerce-events