spring:
  elasticsearch:
    uris: http://localhost:9200
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    com.ecommerce.search: DEBUG
    org.springframework.data.elasticsearch: DEBUG

server:
  port: 8083

kafka:
  topics:
    product-updated: product.events