spring:
  datasource:
    url: jdbc:postgresql://${ORDER_DB_HOST:localhost}:${ORDER_DB_PORT:5436}/${ORDER_DB_NAME:ecommerce_orders}
    username: ${ORDER_DB_USERNAME:postgres}
    password: ${ORDER_DB_PASSWORD:postgres123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

jwt:
  secret: "devSecretKeyForLocalTestingOnly-256bits!"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

product:
  service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8082}

cart:
  service:
    url: ${CART_SERVICE_URL:http://localhost:8084}

logging:
  level:
    com.ecommerce.order: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

payment:
  service:
    url: ${PAYMENT_SERVICE_URL:http://localhost:8086/api/payments}


external:
  kafka:
    enabled: false   # true pour tester l'envoi vers GCP
    bootstrap-servers: 136.115.254.39:9092
    topic: ecommerce-events