spring:
  datasource:
    url: jdbc:postgresql://${PRODUCT_DB_HOST:localhost}:${PRODUCT_DB_PORT:5434}/${PRODUCT_DB_NAME:ecommerce_products}
    username: ${PRODUCT_DB_USERNAME:postgres}
    password: ${PRODUCT_DB_PASSWORD:postgres123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret: "devSecretKeyForLocalTestingOnly-256bits!"