spring:
  datasource:
    url: jdbc:postgresql://${PRODUCT_DB_HOST:localhost}:${PRODUCT_DB_PORT:5432}/${PRODUCT_DB_NAME:ecommerce_products}
    username: ${PRODUCT_DB_USERNAME:postgres}
    password: ${PRODUCT_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    com.ecommerce.product: DEBUG